name: sef_finance

profile: sef_finance

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  sef_finance:
    +schema: raw

models:
  sef_finance:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: table 
    intermediate:
      +materialized: table
    analytics:
      +materialized: table
