version: 2

sources:
  - name: sef_finance_database 
    description: "Raw data from the destination PostgreSQL database."
    database: sef_finance_database
    schema: raw
    tables:
      - name: orders 
        description: "List of orders."
      - name: payments 
        description: "List of Payments."
      - name: users
        description: "List of users."
